const img = (seed) => `https://picsum.photos/seed/${encodeURIComponent(seed)}/480/300`;

export const calendarEvents = [
  {
    id: "1",
    title: "Exclusive Offers and News",
    start: "2025-08-02",
    extendedProps: {
      status: { label: "Ongoing", tone: "warning" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Welcome offer + product updates.",
      image: img("exclusive-offers-news"),
    },
  },
  {
    id: "2",
    title: "Summer Sale - Wave 2",
    start: "2025-08-07",
    extendedProps: {
      status: { label: "Scheduled", tone: "success" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Don't miss out on our summer sale!",
      image: img("summer-sale-wave-2"),
    },
  },
  {
    id: "3",
    title: "Re-engagement Push",
    start: "2025-08-12",
    extendedProps: {
      status: { label: "Scheduled", tone: "info" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "We miss you! Here's a special offer.",
      image: img("re-engagement-push"),
    },
  },
  {
    id: "4",
    title: "Compliance Review",
    start: "2025-08-16",
    extendedProps: {
      status: { label: "Approval pending", tone: "pending" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Pending compliance approval.",
      image: img("compliance-review"),
    },
  },
  {
    id: "5",
    title: "Flash Sale - 24h",
    start: "2025-08-21",
    extendedProps: {
      status: { label: "Aborted", tone: "destructive" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Aborted due to stock issues.",
      image: img("flash-sale-24h"),
    },
  },
  {
    id: "6",
    title: "NPS Survey Blast",
    start: "2025-08-27",
    extendedProps: {
      status: { label: "Draft", tone: "muted" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Help us improve by filling out this survey.",
      image: img("nps-survey-blast"),
    },
  },
  {
    id: "7",
    title: "Festive Offers",
    start: "2025-09-01",
    extendedProps: {
      status: { label: "Ongoing", tone: "warning" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Festive season discounts just for you.",
      image: img("festive-offers"),
    },
  },
  {
    id: "8",
    title: "VIP Early Access",
    start: "2025-09-05",
    extendedProps: {
      status: { label: "Scheduled", tone: "success" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Exclusive access to our VIPs.",
      image: img("vip-early-access"),
    },
  },
  {
    id: "9",
    title: "New Collection Teaser",
    start: "2025-09-07",
    extendedProps: {
      status: { label: "Scheduled", tone: "info" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Get ready for our new collection launch.",
      image: img("new-collection-teaser"),
    },
  },
  {
    id: "10",
    title: "Price Drop Alert",
    start: "2025-09-07",
    extendedProps: {
      status: { label: "Ongoing", tone: "warning" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Big price drops this week.",
      image: img("price-drop-alert"),
    },
  },
  {
    id: "11",
    title: "Weekend Reminder",
    start: "2025-09-14",
    extendedProps: {
      status: { label: "Draft", tone: "muted" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Don't forget our weekend sale.",
      image: img("weekend-reminder"),
    },
  },
  {
    id: "12",
    title: "Bugfix Rollout Notice",
    start: "2025-09-18",
    extendedProps: {
      status: { label: "Approval pending", tone: "pending" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Rollout awaiting approval.",
      image: img("bugfix-rollout-notice"),
    },
  },
  {
    id: "13",
    title: "Clearance Sale",
    start: "2025-09-22",
    extendedProps: {
      status: { label: "Aborted", tone: "destructive" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Sale cancelled due to logistics.",
      image: img("clearance-sale"),
    },
  },
  {
    id: "14",
    title: "Referral Bonus",
    start: "2025-09-28",
    extendedProps: {
      status: { label: "Scheduled", tone: "success" },
      channel: "SMS",
      type: "Broadcast",
      editedOn: "Jul 11, 2023",
      message: "Invite friends and earn rewards.",
      image: img("referral-bonus"),
    },
  },
];
