export const campaigns = [
  {
    id: "1",
    name: "Help enter guided convers...",
    channel: "SMS",
    type: "Broadcast",
    editedOn: "Jul 11, 2023",
    message: "Hey there, This is Soham from ...",
    source: "SaaS",
    recipients: 2,
    status: { label: "Approval pending", tone: "warning" },
    createdOn: "02 Jan 2024",
  },
  {
    id: "2",
    name: "Help enter guided convers...",
    channel: "SMS",
    type: "Broadcast",
    editedOn: "Jul 11, 2023",
    message: "Hello {csv.FIRSTNAME}, Thank...",
    source: "SaaS",
    recipients: 4,
    status: { label: "Draft", tone: "muted" },
    createdOn: "02 Jan 2024",
  },
  {
    id: "3",
    name: "Help enter guided convers...",
    channel: "SMS",
    type: "Broadcast",
    editedOn: "Jul 11, 2023",
    message: "Hey there, This is Soham from ...",
    source: "SaaS",
    recipients: 2,
    status: { label: "Scheduled", tone: "info" },
    createdOn: "02 Jan 2024",
  },
  {
    id: "4",
    name: "Help enter guided convers...",
    channel: "SMS",
    type: "Broadcast",
    editedOn: "Jul 11, 2023",
    message: "Hello {csv.FIRSTNAME}, Thank...",
    source: "SaaS",
    recipients: 2,
    status: { label: "Aborted", tone: "destructive" },
    createdOn: "02 Jan 2024",
  },
  {
    id: "5",
    name: "Help enter guided convers...",
    channel: "SMS",
    type: "Broadcast",
    editedOn: "Jul 11, 2023",
    message: "Conversation flows",
    source: "SaaS",
    recipients: 2,
    status: { label: "Ongoing", tone: "success" },
    createdOn: "02 Jan 2024",
  },
  {
    id: "6",
    name: "Help enter guided convers...",
    channel: "SMS",
    type: "Broadcast",
    editedOn: "Jul 11, 2023",
    message: "Hello {csv.FIRSTNAME}, Thank...",
    source: "SaaS",
    recipients: 2,
    status: { label: "Aborted", tone: "destructive" },
    createdOn: "02 Jan 2024",
  },
];
